### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by freddiehdxd** [chopraaa/video-stream-api#1]
How to use it?

**Comment by Adam759** [comment]
I too am interested in this, it seems to be an API of sorts, documentation would be nice ^^

**Comment by varunchopra** [comment]
I'll try to update it today with instructions for setting it up and running it.

**Comment by Love656** [comment]
Is there an ex link (demo) ?

**Comment by varunchopra** [comment]
@Love656 Sorry, no.

The readme has been updated with more details.
