### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by eudesaess** [chopraaa/video-stream-api#2]
Dude, your code is great. But why does your database request and others not?
Other questions: Does your code encrypt the video url when viewed from source code?
Is there a limit to the daily video views?
I want to use the code to stream the anime. And - hopefully - will have enough traffic. Do you advise me of your code? Appreciate.
Do you accept donation? I like to contribute when I use the code.

**Comment by varunchopra** [comment]
> But why does your database request and others not?

Used only for stats and keeping logs.

> Does your code encrypt the video url when viewed from source code?

I don't feel this is required. It's not possible to receive DMCA on a private video.

>  I want to use the code to stream the anime. And - hopefully - will have enough traffic. Do you advise me of your code? Appreciate.

Google has limits on how much you can access files. So this script works as well as any other.

>  Do you accept donation? I like to contribute when I use the code.

I don't. Sorry.
